/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Browser.Favorites;
import Browser.Historic;
import Database.Database;
import java.awt.BorderLayout;
import javax.swing.JFrame;

public class BrowserInterface extends javax.swing.JFrame {

    public BrowserInterface() {
        initComponents();

        //Cria uma nova tab
        TabInterface tab = new TabInterface();
        //Adiciona a tab à lista de tabs
        Tabs.add(tab.tabBlock);
       
        //inicia a database criando suas tabelas pelo contrutor
        Database database = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnNewTab = new javax.swing.JButton();
        btnConta = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnCloseTab = new javax.swing.JButton();
        btnAddFav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(784, 0));
        setPreferredSize(new java.awt.Dimension(768, 480));

        Tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Tabs.setMinimumSize(new java.awt.Dimension(0, 0));
        Tabs.setPreferredSize(new java.awt.Dimension(0, 0));

        btnNewTab.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnNewTab.setText("Nova Guia");
        btnNewTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewTab(evt);
            }
        });

        btnConta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnConta.setText("Conta");
        btnConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });

        btnHistorico.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnHistorico.setActionCommand("Históric");
        btnHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorico.setLabel("Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        btnFavoritos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnFavoritos.setText("Favoritos");
        btnFavoritos.setActionCommand("Meus Favoritos");
        btnFavoritos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });

        btnCloseTab.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCloseTab.setText("Fechar Tab");
        btnCloseTab.setActionCommand("CloseTab");
        btnCloseTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseTab(evt);
            }
        });

        btnAddFav.setText("Add aos Favoritos");
        btnAddFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCloseTab)
                .addGap(18, 18, 18)
                .addComponent(btnAddFav)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConta)
                        .addComponent(btnHistorico)
                        .addComponent(btnFavoritos)
                        .addComponent(btnCloseTab)
                        .addComponent(btnAddFav))
                    .addComponent(btnNewTab))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        //Cria um frame na tela com o historico
        JFrame frame = new JFrame("Historic");
        HistoricWindow historico = new HistoricWindow();
        frame.getContentPane().add(historico, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        //Cria um frame na tela com os favoritos
        JFrame frame = new JFrame("Favorites");
        FavoriteWindow favoriteWindow = new FavoriteWindow();
        frame.getContentPane().add(favoriteWindow, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void createNewTab(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewTab
        TabInterface tab = new TabInterface();
        //Adiciona a tab à lista de tabs
        Tabs.add(tab.tabBlock);        
    }//GEN-LAST:event_createNewTab

    private void btnCloseTab(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseTab
        int index = Tabs.getSelectedIndex();
        Tabs.remove(index);
        Historic historic = new Historic();
        historic.add("TituloTeste", "01-06-2019", "www.teste.com.br" , 1);
    }//GEN-LAST:event_btnCloseTab

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        //Cria um frame na tela para acessar a conta
        JFrame frame = new JFrame("Conta");
        CountWindow countFrame = new CountWindow();
        frame.getContentPane().add(countFrame, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnAddFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavActionPerformed
        //adiciona aba atual aos favoritos
        
        //Pega aba atual
        //Pega hora atual
        //Pega usuario atual
        //Pega titulo atual
        
        Favorites fav = new Favorites();
        fav.add("Actual Title", "2019-01-01 00:00:00" , "www.pudim.com.br" , 1);
    }//GEN-LAST:event_btnAddFavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton btnAddFav;
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JButton btnConta;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnNewTab;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
