package Interface;

import Browser.Historic;
import Database.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author felpi
 */


public class HistoricWindow extends javax.swing.JPanel {

    /**
     * Creates new form Historico
     */
    public HistoricWindow() {
        initComponents();
        Database database = new Database();
        ResultSet rs = database.GetHistoricTable();
        
        try {
            while (rs.next()) {
                HistoricTestPanel.setText(HistoricTestPanel.getText() + 
                "\n" + rs.getString("DATAHIST") + "   " + rs.getString("TITLE"));
            }
        } 
        catch(SQLException ex)
        {
            System.out.println("Error: " + ex.getMessage());
        }
            
            
        
           
    }
    
    ArrayList<String> histTest; 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TesteHistorico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoricTestPanel = new javax.swing.JEditorPane();

        TesteHistorico.setText("Teste");
        TesteHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteHistoricoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(HistoricTestPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(TesteHistorico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TesteHistorico)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TesteHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane HistoricTestPanel;
    private javax.swing.JButton TesteHistorico;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
