/*
 * Project by Firebird. All rigths reserved to Felpi and Luis.
 */
package Interface;

import Browser.Historic;
import Interpreter.Interpreter;
import Render.Render;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author luise
 */
public class TabInterface extends javax.swing.JPanel {
    JPanel tabBlock;
    
    /**
     * Creates new form TabInterface
     */
    public TabInterface() {
        initComponents();
//        Create new panel which have everything from tab content insite it
        tabBlock = new javax.swing.JPanel();
//        Set table name (page's title)
        Random rand = new Random();
        // Obtain a number between [0 - 49].
        int number = rand.nextInt(50);
        tabBlock.setName("Nova Guia"+number);
        
//      Init toolbar and add to the panel
        ToolbarInterface toolbar = new ToolbarInterface();
        tabBlock.add(toolbar);        
        
//      init mainPanel
        JPanel mainPanel = new JPanel();
        tabBlock.add(mainPanel);        
        
//      Criar arvore
        Interpreter interpreter = new Interpreter();
        interpreter.Interpreter("");

//      Renderiza arvore
        Render render = new Render();
        render.startRender(interpreter, mainPanel, tabBlock);
        
        Historic historic = new Historic();
        historic.add("Historico", "01-06-2019", "www.historicoTeste.com.br" , 1);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(768, 525));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
