/*
 * Project by Firebird. All rigths reserved to Felpi and Luis.
 */
package Interface;

import Interpreter.Interpreter;
import Render.Render;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author luise
 */
public class ToolbarInterface extends javax.swing.JPanel {

    /**
     * Creates new form ToolbarInterface
     */
    public ToolbarInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toolbar = new javax.swing.JPanel();
        url = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 45));
        setPreferredSize(new java.awt.Dimension(1366, 47));

        Toolbar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        url.setMinimumSize(new java.awt.Dimension(200, 25));
        url.setName(""); // NOI18N
        url.setPreferredSize(new java.awt.Dimension(200, 25));
        url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlActionPerformed(evt);
            }
        });

        btnSearch.setText("→");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchsubmitUrl(evt);
            }
        });

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnSearch)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchsubmitUrl(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchsubmitUrl
        //Cria a estrutura de arvores
        Interpreter interpreter = new Interpreter();
        interpreter.Interpreter("");

        //Renderiza a arvore
        Render render = new Render();
        //render.startRender(interpreter, sitePanel);
        
    }//GEN-LAST:event_btnSearchsubmitUrl

    private void urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Toolbar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
